# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'WordRacer' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Fix fmt consteval issue with newer Xcode (auto-patch)
    fmt_base_h = File.join(__dir__, 'Pods/fmt/include/fmt/base.h')
    if File.exist?(fmt_base_h)
      content = File.read(fmt_base_h)
      patched = content.gsub(
        /#elif defined\(__apple_build_version__\) && __apple_build_version__ < \d+L/,
        '#elif defined(__apple_build_version__)'
      )
      if content != patched
        File.write(fmt_base_h, patched)
        Pod::UI.puts "Patched fmt/base.h for Xcode compatibility".green
      end
    end
  end
end
